import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Send, HelpCircle, ChevronDown, ChevronUp } from "lucide-react";

const faqs = [
  { q: "What should I do if a machine overheats?", a: "Immediately stop the machine, report the issue via the Report Issue page, and notify your supervisor. Do not attempt to restart until cleared by maintenance." },
  { q: "How often is routine maintenance performed?", a: "Routine maintenance is scheduled weekly for critical equipment, bi-weekly for medium-risk, and monthly for low-risk machines." },
  { q: "Who do I contact for emergency breakdowns?", a: "Contact the maintenance hotline at ext. 5500 or submit an urgent report through the Report Issue page with 'High' severity." },
  { q: "How are risk levels determined?", a: "Risk levels are calculated by the AI engine based on maintenance logs, equipment age, operating conditions, and historical failure patterns." },
  { q: "Can I view maintenance history for any machine?", a: "Yes, use the AI Chat Assistant and ask about any specific machine ID (e.g., 'Tell me about M-101')." },
  { q: "What safety protocols should I follow near high-risk equipment?", a: "Wear full PPE, maintain safe distance, follow lockout/tagout procedures, and never operate flagged equipment without authorization." },
];

export default function QueryPage() {
  const [search, setSearch] = useState("");
  const [expandedIdx, setExpandedIdx] = useState<number | null>(null);
  const [customQ, setCustomQ] = useState("");
  const [customA, setCustomA] = useState("");

  const filtered = faqs.filter(
    (f) => f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())
  );

  const handleAsk = () => {
    if (!customQ.trim()) return;
    const q = customQ.toLowerCase();
    const match = faqs.find((f) => f.q.toLowerCase().includes(q) || q.includes(f.q.toLowerCase().split(" ").slice(0, 3).join(" ")));
    if (match) {
      setCustomA(match.a);
    } else if (q.includes("maintenance") || q.includes("schedule")) {
      setCustomA("Maintenance schedules are generated by our AI system based on equipment health scores and risk analysis. Check the Dashboard for current schedules.");
    } else if (q.includes("safety") || q.includes("emergency")) {
      setCustomA("For safety emergencies, contact ext. 5500 immediately. Always follow lockout/tagout procedures and wear appropriate PPE.");
    } else {
      setCustomA("Thank you for your question. This has been noted and will be reviewed by the admin team. For immediate assistance, please use the AI Chat Assistant.");
    }
  };

  return (
    <div className="space-y-6 max-w-3xl mx-auto animate-fade-up">
      <div>
        <h1 className="text-2xl font-bold tracking-tight font-display">Help Center</h1>
        <p className="text-sm text-muted-foreground mt-1">Find answers to common questions</p>
      </div>

      {/* Ask a Question */}
      <div className="rounded-xl border bg-card p-6 shadow-sm space-y-4">
        <div className="flex items-center gap-2 text-primary">
          <HelpCircle className="h-5 w-5" />
          <span className="font-semibold text-sm">Ask a Question</span>
        </div>
        <form onSubmit={(e) => { e.preventDefault(); handleAsk(); }} className="flex gap-2">
          <Input value={customQ} onChange={(e) => setCustomQ(e.target.value)} placeholder="Type your question here…" className="flex-1" />
          <Button type="submit" size="icon" disabled={!customQ.trim()}>
            <Send className="h-4 w-4" />
          </Button>
        </form>
        {customA && (
          <div className="rounded-lg bg-secondary p-4 text-sm animate-fade-up">
            <p className="font-semibold text-xs text-primary mb-1">Answer:</p>
            <p>{customA}</p>
          </div>
        )}
      </div>

      {/* FAQ Search */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold font-display">Frequently Asked Questions</h2>
          <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search FAQs…" className="w-60" />
        </div>

        <div className="space-y-2">
          {filtered.map((faq, i) => (
            <div key={i} className="rounded-xl border bg-card shadow-sm overflow-hidden">
              <button
                onClick={() => setExpandedIdx(expandedIdx === i ? null : i)}
                className="flex w-full items-center justify-between p-4 text-left hover:bg-secondary/50 transition-colors"
              >
                <span className="font-medium text-sm">{faq.q}</span>
                {expandedIdx === i ? <ChevronUp className="h-4 w-4 shrink-0 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />}
              </button>
              {expandedIdx === i && (
                <div className="px-4 pb-4 text-sm text-muted-foreground animate-fade-up">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
